### ISSUE TITLE
Action fails with "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by jnewland** [MorrisonCole/pr-lint-action#145]
This action is failing in all places I'm using it during the docker build phase. Attempting to build a Docker image from the contents of the default branch fails as well:

```
$ docker build -t test .
Sending build context to Docker daemon  589.8kB
Step 1/4 : FROM node:slim
 ---> 2870b8b46426
Step 2/4 : COPY . .
 ---> 7682e29f60ee
Step 3/4 : RUN npm install --production
 ---> Running in 368ff935a097
npm notice 
npm notice New patch version of npm available! 7.0.2 -> 7.0.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.3>
npm notice Run `npm install -g npm@7.0.3` to update!
npm notice 
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T22_47_28_615Z-debug.log
The command '/bin/sh -c npm install --production' returned a non-zero code: 1
```

Modifying the command to output any log message returns the following: 

```
$ docker build -t test .
Sending build context to Docker daemon  589.8kB
Step 1/4 : FROM node:slim
 ---> 2870b8b46426
Step 2/4 : COPY . .
 ---> 1f249c7476e2
Step 3/4 : RUN npm install --production || find /root/.npm/_logs/ | xargs cat
 ---> Running in a99fb5443fe1
npm notice 
npm notice New patch version of npm available! 7.0.2 -> 7.0.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.3>
npm notice Run `npm install -g npm@7.0.3` to update!
npm notice 
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T22_47_39_519Z-debug.log
cat: /root/.npm/_logs/: Is a directory
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@7.0.2
2 info using node@v15.0.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session b207d07c5354e513
20 timing npm:load Completed in 14ms
21 http fetch GET 200 https://registry.npmjs.org/npm 337ms
22 http fetch GET 304 https://registry.npmjs.org/npm 63ms (from cache)
23 timing arborist:ctor Completed in 1ms
24 timing idealTree Completed in 17ms
25 timing command:install Completed in 19ms
26 notice New patch version of npm available! 7.0.2 -> 7.0.3
26 notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.3>
26 notice Run `npm install -g npm@7.0.3` to update!
27 verbose stack RangeError: Maximum call stack size exceeded
27 verbose stack     at Node.get parent [as parent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:691:5)
27 verbose stack     at Node.get resolveParent [as resolveParent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:949:17)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:956:32)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
27 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
28 verbose cwd /
29 verbose Linux 4.19.76-linuxkit
30 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
31 verbose node v15.0.0
32 verbose npm  v7.0.2
33 error Maximum call stack size exceeded
34 verbose exit 1
The command '/bin/sh -c npm install --production || find /root/.npm/_logs/ | xargs cat' returned a non-zero code: 12
```

**Comment by MorrisonCole** [comment]
Hey @jnewland! 

Just pushed this out with [v1.4.1](https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.4.1). Confirmed that it at least worked on this test PR: https://github.com/MorrisonCole/pr-lint-action/pull/147.

If you have further trouble in any way though I'm happy to have a proper look! 🙏

**Comment by jnewland** [comment]
Thank you so much @MorrisonCole! 🙇
